/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : string,
  'status' : string,
  'resourceId' : string,
  'name' : string,
  'doneQuestions' : bigint,
  'totalQuestions' : bigint,
}
export interface Resource {
  'id' : string,
  'subject' : string,
  'name' : string,
  'totalChapters' : bigint,
}
export interface RevisionReminder {
  'id' : string,
  'lastReviewed' : bigint,
  'resourceId' : string,
  'chapterId' : string,
  'intervalDays' : bigint,
}
export interface Task {
  'id' : string,
  'status' : string,
  'title' : string,
  'dueDate' : [] | [bigint],
  'description' : string,
  'subjectTag' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChapter' : ActorMethod<
    [string, string, string, bigint, bigint],
    undefined
  >,
  'addResource' : ActorMethod<[string, string, string, bigint], undefined>,
  'addRevisionReminder' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<[string, string, string, [] | [bigint]], string>,
  'deleteChapter' : ActorMethod<[string], undefined>,
  'deleteResource' : ActorMethod<[string], undefined>,
  'deleteRevisionReminder' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'getAllChapters' : ActorMethod<[], Array<Chapter>>,
  'getAllRevisionReminders' : ActorMethod<[], Array<RevisionReminder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChaptersByResource' : ActorMethod<[string], Array<Chapter>>,
  'getDueForRevision' : ActorMethod<[], Array<RevisionReminder>>,
  'getMyTodaySeconds' : ActorMethod<[], bigint>,
  'getResources' : ActorMethod<[], Array<Resource>>,
  'getTasks' : ActorMethod<[[] | [string]], Array<Task>>,
  'getTodayLeaderboard' : ActorMethod<
    [],
    Array<
      { 'totalSeconds' : bigint, 'name' : string, 'principalText' : string }
    >
  >,
  'getTotalChapterCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markRevisionComplete' : ActorMethod<[string], undefined>,
  'recordStudyTime' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateChapterQuestions' : ActorMethod<[string, bigint, bigint], undefined>,
  'updateChapterStatus' : ActorMethod<[string, string], undefined>,
  'updateResource' : ActorMethod<[string, string, string, bigint], undefined>,
  'updateTask' : ActorMethod<
    [string, string, string, string, [] | [bigint], string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];