/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Chapter = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'resourceId' : IDL.Text,
  'name' : IDL.Text,
  'doneQuestions' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
});
export const RevisionReminder = IDL.Record({
  'id' : IDL.Text,
  'lastReviewed' : IDL.Int,
  'resourceId' : IDL.Text,
  'chapterId' : IDL.Text,
  'intervalDays' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Resource = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'totalChapters' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'subjectTag' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChapter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'addResource' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addRevisionReminder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Int)],
      [IDL.Text],
      [],
    ),
  'deleteChapter' : IDL.Func([IDL.Text], [], []),
  'deleteResource' : IDL.Func([IDL.Text], [], []),
  'deleteRevisionReminder' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getAllRevisionReminders' : IDL.Func(
      [],
      [IDL.Vec(RevisionReminder)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChaptersByResource' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], ['query']),
  'getDueForRevision' : IDL.Func([], [IDL.Vec(RevisionReminder)], ['query']),
  'getMyTodaySeconds' : IDL.Func([], [IDL.Nat], ['query']),
  'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getTasks' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Task)], ['query']),
  'getTodayLeaderboard' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'totalSeconds' : IDL.Nat,
            'name' : IDL.Text,
            'principalText' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getTotalChapterCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markRevisionComplete' : IDL.Func([IDL.Text], [], []),
  'recordStudyTime' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChapterQuestions' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'updateChapterStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateResource' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Int), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'resourceId' : IDL.Text,
    'name' : IDL.Text,
    'doneQuestions' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
  });
  const RevisionReminder = IDL.Record({
    'id' : IDL.Text,
    'lastReviewed' : IDL.Int,
    'resourceId' : IDL.Text,
    'chapterId' : IDL.Text,
    'intervalDays' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Resource = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'totalChapters' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'subjectTag' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChapter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addResource' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addRevisionReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Int)],
        [IDL.Text],
        [],
      ),
    'deleteChapter' : IDL.Func([IDL.Text], [], []),
    'deleteResource' : IDL.Func([IDL.Text], [], []),
    'deleteRevisionReminder' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getAllRevisionReminders' : IDL.Func(
        [],
        [IDL.Vec(RevisionReminder)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChaptersByResource' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Chapter)],
        ['query'],
      ),
    'getDueForRevision' : IDL.Func([], [IDL.Vec(RevisionReminder)], ['query']),
    'getMyTodaySeconds' : IDL.Func([], [IDL.Nat], ['query']),
    'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getTasks' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Task)], ['query']),
    'getTodayLeaderboard' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'totalSeconds' : IDL.Nat,
              'name' : IDL.Text,
              'principalText' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getTotalChapterCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markRevisionComplete' : IDL.Func([IDL.Text], [], []),
    'recordStudyTime' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChapterQuestions' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'updateChapterStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Int), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };